version: "3"
services:
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user_id: ${USER_ID}
    volumes:
      - ./home:/home/jupyter/host_data
    ports:
      - "8887:8888"
    expose:
      - "8887"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
